@echo off
SET ENVIRONMENT_NAME=print_pi_env
SET MINICONDA_INSTALL_SCRIPT=%~dp0\miniconda3_64_install.bat
SET MINICONDA_INSTALL_FOLDER=%UserProfile%\miniconda3_64
SET LOCAL_ENVIRONMENT_FOLDER=%MINICONDA_INSTALL_FOLDER%\envs\%ENVIRONMENT_NAME%
SET MINICONDA_SETUP_FILENAME=Miniconda3-latest-Windows-x86_64.exe
SET MINICONDA_DOWNLOAD_FOLDER=%UserProfile%\Downloads
SET MINICONDA_DOWNLOAD_URL=https://repo.anaconda.com/miniconda/%MINICONDA_SETUP_FILENAME%
